# Options for analysis running.
version: "2"
linters:
  enable:
    - cyclop
    - nestif
    - bodyclose
    - iface
    - gosec

  exclusions:
    paths: "example/*"
    rules:
      - path: '(.+)_test\.go'
        linters:
          - gosec



