---
name: pull request

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-scan:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.16]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: test
        run: go test ./...

      - name: go sec
        uses: securego/gosec@master
        with:
          args: ./...
