---
name: pull request

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-scan:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.16.6]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goVer }} # The Go version to download (if necessary) and use.

      - name: test
        run: make test
