---
name: pull request

on:
  pull_request:
    branches:
      - main

env:
  GOLANG_VERSION: 1.22

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
         
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: install tools
        run: make get-tools

      - name: test
        run: make test-unit lint scan
