---
name: pull request

on:
  pull_request:
    branches:
      - main


jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
         
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          
      - name: install tools
        run: make get-tools

      - name: test
        run: make test-unit lint scan
