name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: codfish/semantic-release-action@v3.0.0
        with:
          plugins: |
            [ '@semantic-release/github' ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
